package cn.wzz.mapper;

import java.util.List;

import cn.wzz.bean.CaseBatch;

public interface CaseBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int insert(CaseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    List<CaseBatch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int updateByPrimaryKey(CaseBatch record);
}