package cn.wzz.mapper;

import java.util.List;

import cn.wzz.bean.CaseInfo;

public interface CaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int insert(CaseInfo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    List<CaseInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int updateByPrimaryKey(CaseInfo record);
}