package cn.wzz.mapper;

import cn.wzz.bean.CasePaid;
import java.util.List;

public interface CasePaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int insert(CasePaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    CasePaid selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    List<CasePaid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int updateByPrimaryKey(CasePaid record);
}