package cn.wzz.mapper;

import java.util.List;

import cn.wzz.bean.CaseApply;

public interface CaseApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int insert(CaseApply record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    List<CaseApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int updateByPrimaryKey(CaseApply record);
}