package cn.wzz.mapper;

import java.util.List;

import cn.wzz.bean.CaseLinkman;

public interface CaseLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int insert(CaseLinkman record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    List<CaseLinkman> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_linkman
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int updateByPrimaryKey(CaseLinkman record);
}