package cn.wzz.mapper;

import java.util.List;
import java.util.Map;

import cn.wzz.bean.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int updateByPrimaryKey(Employee record);

	int editUpdateIn(Map<String, Object> paramMap);

	int editUpdateUp(Map<String, Object> paramMap);

	List<Employee> selectEmp(Map<Object,Object> map);
}