package cn.wzz.mapper;

import java.util.List;

import cn.wzz.bean.Entrust;

public interface EntrustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int insert(Entrust record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    List<Entrust> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    int updateByPrimaryKey(Entrust record);
}