package cn.wzz.mapper;

import java.util.List;
import java.util.Map;

import cn.wzz.bean.Organization;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    List<Organization> selectOrg(Map<Object,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    Organization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    List<Organization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    int updateByPrimaryKey(Organization record);

}