package cn.wzz.mapper;

import cn.wzz.bean.PhoneRecord;
import java.util.List;

public interface PhoneRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int insert(PhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    PhoneRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    List<PhoneRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int updateByPrimaryKey(PhoneRecord record);
}