package cn.wzz.mapper;

import cn.wzz.bean.Position;
import java.util.List;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    Position selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Tue Apr 24 10:13:42 CST 2018
     */
    int updateByPrimaryKey(Position record);
}