package cn.wzz.mapper;

import java.util.List;

import cn.wzz.bean.VisitRecord;

public interface VisitRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int insert(VisitRecord record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    List<VisitRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated Tue Apr 24 11:12:37 CST 2018
     */
    int updateByPrimaryKey(VisitRecord record);
}