package cn.wzz.bean;

import java.math.BigDecimal;
import java.util.Date;

public class CaseBatch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.batch_code
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String batchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.state
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.version
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.entrust_product_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String entrustProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.entrust_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.total_money
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private BigDecimal totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.total_number
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Integer totalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.type_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.begin_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.area_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.end_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.actual_end_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Date actualEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.create_emp_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String modifyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.target
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private BigDecimal target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.achieve
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private BigDecimal achieve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.collection_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.batch_xls
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String batchXls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.upload_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.modify_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.create_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.bath_tips
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String bathTips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.status
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.wdc_desc
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String wdcDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.is_upload
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private Integer isUpload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.template_type
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.handle
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String handle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.remark
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_batch.batch_log
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    private String batchLog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.id
     *
     * @return the value of case_batch.id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.id
     *
     * @param id the value for case_batch.id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.batch_code
     *
     * @return the value of case_batch.batch_code
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.batch_code
     *
     * @param batchCode the value for case_batch.batch_code
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.state
     *
     * @return the value of case_batch.state
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.state
     *
     * @param state the value for case_batch.state
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.version
     *
     * @return the value of case_batch.version
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.version
     *
     * @param version the value for case_batch.version
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.entrust_product_id
     *
     * @return the value of case_batch.entrust_product_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getEntrustProductId() {
        return entrustProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.entrust_product_id
     *
     * @param entrustProductId the value for case_batch.entrust_product_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setEntrustProductId(String entrustProductId) {
        this.entrustProductId = entrustProductId == null ? null : entrustProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.entrust_id
     *
     * @return the value of case_batch.entrust_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.entrust_id
     *
     * @param entrustId the value for case_batch.entrust_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setEntrustId(String entrustId) {
        this.entrustId = entrustId == null ? null : entrustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.total_money
     *
     * @return the value of case_batch.total_money
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.total_money
     *
     * @param totalMoney the value for case_batch.total_money
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.total_number
     *
     * @return the value of case_batch.total_number
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Integer getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.total_number
     *
     * @param totalNumber the value for case_batch.total_number
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setTotalNumber(Integer totalNumber) {
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.type_id
     *
     * @return the value of case_batch.type_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.type_id
     *
     * @param typeId the value for case_batch.type_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.begin_date
     *
     * @return the value of case_batch.begin_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.begin_date
     *
     * @param beginDate the value for case_batch.begin_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.area_id
     *
     * @return the value of case_batch.area_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.area_id
     *
     * @param areaId the value for case_batch.area_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.end_date
     *
     * @return the value of case_batch.end_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.end_date
     *
     * @param endDate the value for case_batch.end_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.actual_end_date
     *
     * @return the value of case_batch.actual_end_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Date getActualEndDate() {
        return actualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.actual_end_date
     *
     * @param actualEndDate the value for case_batch.actual_end_date
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.create_emp_id
     *
     * @return the value of case_batch.create_emp_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.create_emp_id
     *
     * @param createEmpId the value for case_batch.create_emp_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.modify_emp_id
     *
     * @return the value of case_batch.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.modify_emp_id
     *
     * @param modifyEmpId the value for case_batch.modify_emp_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setModifyEmpId(String modifyEmpId) {
        this.modifyEmpId = modifyEmpId == null ? null : modifyEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.target
     *
     * @return the value of case_batch.target
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public BigDecimal getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.target
     *
     * @param target the value for case_batch.target
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setTarget(BigDecimal target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.achieve
     *
     * @return the value of case_batch.achieve
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public BigDecimal getAchieve() {
        return achieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.achieve
     *
     * @param achieve the value for case_batch.achieve
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setAchieve(BigDecimal achieve) {
        this.achieve = achieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.collection_id
     *
     * @return the value of case_batch.collection_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.collection_id
     *
     * @param collectionId the value for case_batch.collection_id
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setCollectionId(String collectionId) {
        this.collectionId = collectionId == null ? null : collectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.batch_xls
     *
     * @return the value of case_batch.batch_xls
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getBatchXls() {
        return batchXls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.batch_xls
     *
     * @param batchXls the value for case_batch.batch_xls
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setBatchXls(String batchXls) {
        this.batchXls = batchXls == null ? null : batchXls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.upload_time
     *
     * @return the value of case_batch.upload_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.upload_time
     *
     * @param uploadTime the value for case_batch.upload_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.modify_time
     *
     * @return the value of case_batch.modify_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.modify_time
     *
     * @param modifyTime the value for case_batch.modify_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.create_time
     *
     * @return the value of case_batch.create_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.create_time
     *
     * @param createTime the value for case_batch.create_time
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.bath_tips
     *
     * @return the value of case_batch.bath_tips
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getBathTips() {
        return bathTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.bath_tips
     *
     * @param bathTips the value for case_batch.bath_tips
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setBathTips(String bathTips) {
        this.bathTips = bathTips == null ? null : bathTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.status
     *
     * @return the value of case_batch.status
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.status
     *
     * @param status the value for case_batch.status
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.wdc_desc
     *
     * @return the value of case_batch.wdc_desc
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getWdcDesc() {
        return wdcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.wdc_desc
     *
     * @param wdcDesc the value for case_batch.wdc_desc
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setWdcDesc(String wdcDesc) {
        this.wdcDesc = wdcDesc == null ? null : wdcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.is_upload
     *
     * @return the value of case_batch.is_upload
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public Integer getIsUpload() {
        return isUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.is_upload
     *
     * @param isUpload the value for case_batch.is_upload
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setIsUpload(Integer isUpload) {
        this.isUpload = isUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.template_type
     *
     * @return the value of case_batch.template_type
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.template_type
     *
     * @param templateType the value for case_batch.template_type
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setTemplateType(String templateType) {
        this.templateType = templateType == null ? null : templateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.handle
     *
     * @return the value of case_batch.handle
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.handle
     *
     * @param handle the value for case_batch.handle
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setHandle(String handle) {
        this.handle = handle == null ? null : handle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.remark
     *
     * @return the value of case_batch.remark
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.remark
     *
     * @param remark the value for case_batch.remark
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_batch.batch_log
     *
     * @return the value of case_batch.batch_log
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public String getBatchLog() {
        return batchLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_batch.batch_log
     *
     * @param batchLog the value for case_batch.batch_log
     *
     * @mbggenerated Sat Apr 21 10:12:52 CST 2018
     */
    public void setBatchLog(String batchLog) {
        this.batchLog = batchLog == null ? null : batchLog.trim();
    }
}